### ISSUE TITLE
Question about parameterizing for modified amino acid

### ISSUE THREAD

**Issue by shaoqx** [arwalkerlab/AutoParams#1]
Dear AutoParams Developer,

This is an exciting tool! I want to use it for parameterizing modified amino acids. Would just supplying head and tail atom names in the batch application work? 
I found in the pipeline, the MOL2 file is modified by adding head and tail information. How would it compare to the workflow suggested on the Amber website (http://ambermd.org/tutorials/basic/tutorial5/)?
Thank you!

All the Best,
QZ

**Comment by markahix** [comment]
Hello QZ,

Short answer first:  Yes, you can simply supply the HEAD and TAIL atom names as they appear in your PDB to the batchmode script or the browser UI, and AutoParams will include the information in the MOL2 file automatically.

Long Answer:  If you provide a PDB structure for a subunit of a larger polymeric system, such as a modified amino acid, nucleic acid, etc., and include the HEAD and TAIL atoms in the job submission, AutoParams will identify these atoms during the subsequent calculations and processes.  If you cap the ends of your subunits (such as with a methyl group), include the atom names of the caps in the appropriate field on the browser UI and AutoParams will account for them during RESP fitting, then remove them before generating the MOL2 to prevent non-integer molecular charges.  It will then include the HEAD and TAIL atoms in the MOL2 and allow you to incorporate the monomer subunit into larger sequences, such as one might with a functionalized AA in a protein.

This will give you the MOL2 and FRCMOD files, at which point you can start at Section 4 of the [linked tutorial above](http://ambermd.org/tutorials/basic/tutorial5/), changing the input for tleap slightly.

`CRO = loadmol2 CRO.mol2
loadamberparams CRO.frcmod
`

Hope this helps!

- Mark A. Hix
