### ISSUE TITLE
Error parametrizing Azide Nucleophile

### ISSUE THREAD

**Issue by miqueleg** [arwalkerlab/AutoParams#2]
Using the docker version that uses Python 3.10, I tried multiple substrates for proteins, and the program worked fine (Optimization crashes, but I do not need it).

My problem arises when trying to parameterize the Azide ion (SMILES: [N-]=[N+]=[N-] ).
When the program recognizes the protonation of the azide, It fails to show me the molecule and the parameter files.
![Screenshot](https://github.com/arwalkerlab/AutoParams/assets/33085433/a6f8e2cb-3be6-4bad-a202-28661cd12c13)
[AZIDE INPUT PDB.zip](https://github.com/arwalkerlab/AutoParams/files/13240857/AZI.zip)

I hope it is a simple error or an error on my part.
Thanks

**Comment by markahix** [comment]
Hi @miqueleg ,
I've tried your PDB and while I get a similar issue with the final display (admittedly that functionality still needs some work), I was able to get the frcmod/mol2 files without issue.

![image](https://github.com/arwalkerlab/AutoParams/assets/42051926/cd33cc61-2df6-4567-abb5-1cda4ea492da)

I have attached the outputs below for your convenience, and I will take a look into the docker container running py3.10 to see if there's something wrong in the image.
[Azide.zip](https://github.com/arwalkerlab/AutoParams/files/13242425/Azide.zip)

**Comment by miqueleg** [comment]
Hi @markahix,

Thanks for the fast answer.
Yes, I hope with a little bit of work, the visualization functionality works better, but is not a problem at all. This tool can be of nice help for lots of projects.
Thanks for the parameter files; I hope it is just a problem with the docker image in the 3.10 version. Which version do you recommend to use? I also tried to use the repository directly, but I failed to properly use the flask command, so in the end, I used the docker (much easier).

Also, on a tangent, and I fear that is not a problem from your code, but maybe antechamber or parmchk, I tried Azide specifically because I know that these programs fail to describe the parameters for this molecule, and the files you sent me have the parameters for the angle wrong. Azide must be a linear molecule, and I do not know how to get the angle parameters using other software. I think that the atom names get confused with other nitrogen atoms in GAFF.
